# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/CreateModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CreateModel(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 400)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.return_button = QtWidgets.QPushButton(self.centralwidget)
        self.return_button.setGeometry(QtCore.QRect(10, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.return_button.setFont(font)
        self.return_button.setObjectName("return_button")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(180, 100, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.link_label = QtWidgets.QLabel(self.centralwidget)
        self.link_label.setGeometry(QtCore.QRect(180, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.link_label.setFont(font)
        self.link_label.setObjectName("link_label")
        self.link = QtWidgets.QLineEdit(self.centralwidget)
        self.link.setGeometry(QtCore.QRect(170, 190, 291, 31))
        self.link.setStyleSheet("QLineEdit\n"
                                "{\n"
                                "border: 2px solid black;\n"
                                "border-radius: 15px;\n"
                                "}")
        self.link.setObjectName("link")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(170, 120, 291, 31))
        self.name.setStyleSheet("QLineEdit\n"
                                "{\n"
                                "border: 2px solid black;\n"
                                "border-radius: 15px;\n"
                                "}")
        self.name.setObjectName("name")
        self.createmodel_button = QtWidgets.QPushButton(self.centralwidget)
        self.createmodel_button.setGeometry(QtCore.QRect(260, 250, 111, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.createmodel_button.setFont(font)
        self.createmodel_button.setStyleSheet("")
        self.createmodel_button.setObjectName("createmodel_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.return_button.setText(_translate("MainWindow", "<"))
        self.name_label.setText(_translate("MainWindow", "Назва"))
        self.link_label.setText(_translate("MainWindow", "Посидання"))
        self.createmodel_button.setText(
            _translate("MainWindow", "Додати модель"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = CreateModel()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
