# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Materials.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Materials(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 388)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.line = QtWidgets.QLabel(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 50, 611, 16))
        self.line.setObjectName("line")
        self.models_button = QtWidgets.QPushButton(self.centralwidget)
        self.models_button.setEnabled(True)
        self.models_button.setGeometry(QtCore.QRect(90, 30, 75, 23))
        self.models_button.setObjectName("models_button")
        self.profile_button = QtWidgets.QPushButton(self.centralwidget)
        self.profile_button.setGeometry(QtCore.QRect(170, 30, 75, 23))
        self.profile_button.setObjectName("profile_button")
        self.materials_label = QtWidgets.QLabel(self.centralwidget)
        self.materials_label.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.materials_label.setStyleSheet(
            "background-color: rgb(177, 177, 177);")
        self.materials_label.setObjectName("materials_label")
        self.addmaterial_button = QtWidgets.QPushButton(self.centralwidget)
        self.addmaterial_button.setGeometry(QtCore.QRect(510, 70, 111, 31))
        self.addmaterial_button.setObjectName("addmaterial_button")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 100, 601, 271))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(26, 73, 291, 31))
        self.label.setObjectName("label")
        self.scrollArea.raise_()
        self.line.raise_()
        self.models_button.raise_()
        self.profile_button.raise_()
        self.materials_label.raise_()
        self.addmaterial_button.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.loadMaterials()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.line.setText(_translate(
            "MainWindow", "____________________________________________________________________________________________________"))
        self.models_button.setText(_translate("MainWindow", "Моделі"))
        self.profile_button.setText(_translate("MainWindow", "Профіль"))
        self.materials_label.setText(_translate("MainWindow", "  Матеріали"))
        self.addmaterial_button.setText(
            _translate("MainWindow", "Додати матеріал"))
        self.label.setText(_translate("MainWindow", "Матеріали"))

    def materialClick(self, event):
        ui.startUIProfile()

    # TODO make fucking load and clear prints
    def loadMaterials(self):
        _translate = QtCore.QCoreApplication.translate
        try:
            with connect(
                host="localhost",
                user="root",
                password="",
                database="pyfuture",
            ) as connection:
                get_value_table_query = "SELECT * FROM users WHERE login = 'temp'"
                with connection.cursor() as cursor:
                    cursor.execute(get_value_table_query)
                    temp = cursor.fetchall()

                    for row in temp:
                        print(row)
                        self.groupBox = QtWidgets.QGroupBox(
                            self.scrollAreaWidgetContents)
                        self.groupBox.setMinimumSize(QtCore.QSize(0, 70))
                        self.groupBox.setMaximumSize(
                            QtCore.QSize(16777215, 70))
                        self.groupBox.setStyleSheet(
                            "background-color: rgb(255, 255, 255);")
                        self.groupBox.setTitle("")
                        self.groupBox.setObjectName("groupBox")
                        self.groupBox.mousePressEvent = self.materialClick
                        self.name_label = QtWidgets.QLabel(self.groupBox)
                        self.name_label.setGeometry(
                            QtCore.QRect(10, 10, 47, 13))
                        self.name_label.setObjectName("name_label")
                        self.date_label = QtWidgets.QLabel(self.groupBox)
                        self.date_label.setGeometry(
                            QtCore.QRect(480, 50, 81, 16))
                        self.date_label.setObjectName("date_label")
                        self.author_label = QtWidgets.QLabel(self.groupBox)
                        self.author_label.setGeometry(
                            QtCore.QRect(10, 50, 47, 13))
                        self.author_label.setObjectName("author_label")
                        self.date_label.raise_()
                        self.name_label.raise_()
                        self.author_label.raise_()
                        self.name_label.setText(
                            _translate("MainWindow", row[3]))
                        self.date_label.setText(
                            _translate("MainWindow", row[5]))
                        self.author_label.setText(
                            _translate("MainWindow", row[8] + " " + row[7] + " " + row[9]))
                        self.verticalLayout.addWidget(self.groupBox)

                    # self.name_label.setText(
                    #     user[9] + " " + user[8] + " " + user[10])

        except Error as e:
            print(e)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyProgram = QtWidgets.QDialog()
    ui = Ui_PyProgram()
    ui.setupUi(PyProgram)
    PyProgram.show()
    sys.exit(app.exec_())
