# -*- coding: utf-8 -*-

# MainWindow implementation generated from reading ui file 'ui/Model.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets


class Model(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 400)
        self.return_button = QtWidgets.QPushButton(MainWindow)
        self.return_button.setGeometry(QtCore.QRect(20, 20, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.return_button.setFont(font)
        self.return_button.setObjectName("return_button")
        self.textBrowser = QtWebEngineWidgets.QWebEngineView(MainWindow)
        self.textBrowser.setGeometry(QtCore.QRect(20, 60, 601, 321))
        self.textBrowser.load(QtCore.QUrl('https://google.com'))
        # self.textBrowser.append('<p>lorem</p>')
        # self.textBrowser.append(
        #     '<a href="https://google.com">jhashkfjaskj</a>')
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.return_button.setText(_translate("MainWindow", "<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
