# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Models.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 400)
        self.line = QtWidgets.QLabel(Form)
        self.line.setGeometry(QtCore.QRect(20, 50, 611, 16))
        self.line.setObjectName("line")
        self.models_label = QtWidgets.QLabel(Form)
        self.models_label.setGeometry(QtCore.QRect(100, 30, 61, 21))
        self.models_label.setStyleSheet("background-color: rgb(177, 177, 177);\n"
"")
        self.models_label.setAlignment(QtCore.Qt.AlignCenter)
        self.models_label.setObjectName("models_label")
        self.profile_button = QtWidgets.QPushButton(Form)
        self.profile_button.setGeometry(QtCore.QRect(170, 30, 75, 23))
        self.profile_button.setObjectName("profile_button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(26, 73, 291, 31))
        self.label.setObjectName("label")
        self.materials_button = QtWidgets.QPushButton(Form)
        self.materials_button.setEnabled(True)
        self.materials_button.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.materials_button.setObjectName("materials_button")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(20, 100, 601, 291))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 289))
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.name_label = QtWidgets.QLabel(self.groupBox)
        self.name_label.setGeometry(QtCore.QRect(10, 10, 561, 51))
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.addmodel_button = QtWidgets.QPushButton(Form)
        self.addmodel_button.setGeometry(QtCore.QRect(510, 70, 111, 31))
        self.addmodel_button.setObjectName("addmodel_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.line.setText(_translate("Form", "____________________________________________________________________________________________________"))
        self.models_label.setText(_translate("Form", "Моделі"))
        self.profile_button.setText(_translate("Form", "Профіль"))
        self.label.setText(_translate("Form", "Моделі"))
        self.materials_button.setText(_translate("Form", "Матеріали"))
        self.name_label.setText(_translate("Form", "Закон Ома"))
        self.addmodel_button.setText(_translate("Form", "Додати модель"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
