# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Ohmmodel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 380)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.obvodka_textbrowser = QtWidgets.QTextBrowser(Dialog)
        self.obvodka_textbrowser.setGeometry(QtCore.QRect(180, 90, 281, 111))
        self.obvodka_textbrowser.setStyleSheet("QTextBrowser\n"
                                               "{\n"
                                               "background-color: rgba(255, 255, 255, 0);\n"
                                               "border: 2px solid black;\n"
                                               "border-radius: 15px;\n"
                                               "}")
        self.obvodka_textbrowser.setObjectName("obvodka_textbrowser")
        self.amper_label = QtWidgets.QLabel(Dialog)
        self.amper_label.setGeometry(QtCore.QRect(290, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.amper_label.setFont(font)
        self.amper_label.setObjectName("amper_label")
        self.return_button = QtWidgets.QPushButton(Dialog)
        self.return_button.setGeometry(QtCore.QRect(20, 20, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.return_button.setFont(font)
        self.return_button.setObjectName("return_button")
        self.obvodkares_textbrowser = QtWidgets.QTextBrowser(Dialog)
        self.obvodkares_textbrowser.setGeometry(QtCore.QRect(50, 260, 141, 91))
        self.obvodkares_textbrowser.setStyleSheet("QTextBrowser\n"
                                                  "{\n"
                                                  "background-color: rgba(255, 255, 255, 0);\n"
                                                  "border: 1px solid black;\n"
                                                  "border-radius: 15px;\n"
                                                  "}")
        self.obvodkares_textbrowser.setObjectName("obvodkares_textbrowser")
        self.res_label = QtWidgets.QLabel(Dialog)
        self.res_label.setGeometry(QtCore.QRect(110, 270, 47, 13))
        self.res_label.setObjectName("res_label")
        self.vimirres_label = QtWidgets.QLabel(Dialog)
        self.vimirres_label.setGeometry(QtCore.QRect(70, 290, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vimirres_label.setFont(font)
        self.vimirres_label.setObjectName("vimirres_label")
        self.oneres_label = QtWidgets.QLabel(Dialog)
        self.oneres_label.setGeometry(QtCore.QRect(70, 330, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.oneres_label.setFont(font)
        self.oneres_label.setObjectName("oneres_label")
        self.stores_label = QtWidgets.QLabel(Dialog)
        self.stores_label.setGeometry(QtCore.QRect(150, 330, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stores_label.setFont(font)
        self.stores_label.setObjectName("stores_label")
        self.tenvolt_label = QtWidgets.QLabel(Dialog)
        self.tenvolt_label.setGeometry(QtCore.QRect(490, 330, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tenvolt_label.setFont(font)
        self.tenvolt_label.setObjectName("tenvolt_label")
        self.obvodkavolt_textbrowser = QtWidgets.QTextBrowser(Dialog)
        self.obvodkavolt_textbrowser.setGeometry(
            QtCore.QRect(470, 260, 141, 91))
        self.obvodkavolt_textbrowser.setStyleSheet("QTextBrowser\n"
                                                   "{\n"
                                                   "background-color: rgba(255, 255, 255, 0);\n"
                                                   "border: 1px solid black;\n"
                                                   "border-radius: 15px;\n"
                                                   "}")
        self.obvodkavolt_textbrowser.setObjectName("obvodkavolt_textbrowser")
        self.vimirvolt_label = QtWidgets.QLabel(Dialog)
        self.vimirvolt_label.setGeometry(QtCore.QRect(490, 290, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vimirvolt_label.setFont(font)
        self.vimirvolt_label.setObjectName("vimirvolt_label")
        self.volt_label = QtWidgets.QLabel(Dialog)
        self.volt_label.setGeometry(QtCore.QRect(520, 270, 51, 16))
        self.volt_label.setObjectName("volt_label")
        self.tisyachavolt_label = QtWidgets.QLabel(Dialog)
        self.tisyachavolt_label.setGeometry(QtCore.QRect(570, 330, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tisyachavolt_label.setFont(font)
        self.tisyachavolt_label.setObjectName("tisyachavolt_label")
        self.res_slider = QtWidgets.QSlider(Dialog)
        self.res_slider.setGeometry(QtCore.QRect(60, 310, 121, 22))
        self.res_slider.setMinimum(1)
        self.res_slider.setMaximum(100)
        self.res_slider.setOrientation(QtCore.Qt.Horizontal)
        self.res_slider.setInvertedAppearance(False)
        self.res_slider.setInvertedControls(False)
        self.res_slider.setObjectName("res_slider")
        self.volt_slider = QtWidgets.QSlider(Dialog)
        self.volt_slider.setGeometry(QtCore.QRect(480, 310, 121, 22))
        self.volt_slider.setMinimum(1)
        self.volt_slider.setMaximum(100)
        self.volt_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volt_slider.setInvertedAppearance(False)
        self.volt_slider.setInvertedControls(False)
        self.volt_slider.setObjectName("volt_slider")
        self.lastPoint = QtWidgets.QLabel(Dialog)
        self.lastPoint.setGeometry(QtCore.QRect(405, 250, 2, 2))
        self.lastPoint.setStyleSheet("background-color: #000")
        self.lastPoint.setText("")
        self.lastPoint.setObjectName("lastPoint")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(210, 160, 221, 91))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.cylindr_label = QtWidgets.QLabel(self.groupBox)
        self.cylindr_label.setGeometry(QtCore.QRect(0, 0, 221, 91))
        self.cylindr_label.setToolTipDuration(0)
        self.cylindr_label.setStyleSheet("")
        self.cylindr_label.setText("")
        self.cylindr_label.setPixmap(
            QtGui.QPixmap("ui\\../img/exp/cylinder.png"))
        self.cylindr_label.setScaledContents(True)
        self.cylindr_label.setObjectName("cylindr_label")
        self.firstPoint = QtWidgets.QLabel(self.groupBox)
        self.firstPoint.setGeometry(QtCore.QRect(190, 80, 2, 2))
        self.firstPoint.setStyleSheet("background-color: #000")
        self.firstPoint.setText("")
        self.firstPoint.setObjectName("firstPoint")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.amper_label.setText(_translate("Dialog", "I = 9.90 A"))
        self.return_button.setText(_translate("Dialog", "<"))
        self.res_label.setText(_translate("Dialog", "Опір"))
        self.vimirres_label.setText(_translate("Dialog", "51"))
        self.oneres_label.setText(_translate("Dialog", "1"))
        self.stores_label.setText(_translate("Dialog", "100"))
        self.tenvolt_label.setText(_translate("Dialog", "10"))
        self.vimirvolt_label.setText(_translate("Dialog", "505"))
        self.volt_label.setText(_translate("Dialog", "Вольтаж"))
        self.tisyachavolt_label.setText(_translate("Dialog", "1000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
