# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 360)
        self.icon_button = QtWidgets.QPushButton(Dialog)
        self.icon_button.setGeometry(QtCore.QRect(270, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.icon_button.setFont(font)
        self.icon_button.setStyleSheet("")
        self.icon_button.setObjectName("icon_button")
        self.surname_label = QtWidgets.QLabel(Dialog)
        self.surname_label.setGeometry(QtCore.QRect(190, 110, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.surname_label.setFont(font)
        self.surname_label.setObjectName("surname_label")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setGeometry(QtCore.QRect(400, 110, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.surname = QtWidgets.QLineEdit(Dialog)
        self.surname.setGeometry(QtCore.QRect(140, 130, 171, 31))
        self.surname.setStyleSheet("QLineEdit\n"
"{\n"
"border: 2px solid black;\n"
"border-radius: 15px;\n"
"}")
        self.surname.setObjectName("surname")
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(330, 130, 171, 31))
        self.name.setStyleSheet("QLineEdit\n"
"{\n"
"border: 2px solid black;\n"
"border-radius: 15px;\n"
"}")
        self.name.setObjectName("name")
        self.pobat_label = QtWidgets.QLabel(Dialog)
        self.pobat_label.setGeometry(QtCore.QRect(190, 200, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pobat_label.setFont(font)
        self.pobat_label.setObjectName("pobat_label")
        self.email_label = QtWidgets.QLabel(Dialog)
        self.email_label.setGeometry(QtCore.QRect(400, 200, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.pobat = QtWidgets.QLineEdit(Dialog)
        self.pobat.setGeometry(QtCore.QRect(140, 220, 171, 31))
        self.pobat.setStyleSheet("QLineEdit\n"
"{\n"
"border: 2px solid black;\n"
"border-radius: 15px;\n"
"}")
        self.pobat.setObjectName("pobat")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(330, 220, 171, 31))
        self.email.setStyleSheet("QLineEdit\n"
"{\n"
"border: 2px solid black;\n"
"border-radius: 15px;\n"
"}")
        self.email.setObjectName("email")
        self.save_button = QtWidgets.QPushButton(Dialog)
        self.save_button.setGeometry(QtCore.QRect(270, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("")
        self.save_button.setObjectName("save_button")
        self.return_button = QtWidgets.QPushButton(Dialog)
        self.return_button.setGeometry(QtCore.QRect(10, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.return_button.setFont(font)
        self.return_button.setObjectName("return_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.icon_button.setText(_translate("Dialog", "Аватар"))
        self.surname_label.setText(_translate("Dialog", "Прізвище"))
        self.name_label.setText(_translate("Dialog", "Ім\'я"))
        self.pobat_label.setText(_translate("Dialog", "По-батькові"))
        self.email_label.setText(_translate("Dialog", "Email"))
        self.save_button.setText(_translate("Dialog", "Зберегти"))
        self.return_button.setText(_translate("Dialog", "<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
