# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newui/Profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 380)
        self.line = QtWidgets.QLabel(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 50, 611, 16))
        self.line.setObjectName("line")
        self.models_button = QtWidgets.QPushButton(Dialog)
        self.models_button.setGeometry(QtCore.QRect(100, 30, 75, 23))
        self.models_button.setStyleSheet(
            "background-color: rgb(53, 132, 228);")
        self.models_button.setObjectName("models_button")
        self.materials_button = QtWidgets.QPushButton(Dialog)
        self.materials_button.setGeometry(QtCore.QRect(20, 30, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.materials_button.setFont(font)
        self.materials_button.setStyleSheet(
            "background-color: rgb(53, 132, 228);")
        self.materials_button.setObjectName("materials_button")
        self.profile_label = QtWidgets.QLabel(Dialog)
        self.profile_label.setGeometry(QtCore.QRect(187, 31, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.profile_label.setFont(font)
        self.profile_label.setStyleSheet(
            "background-color: rgb(154, 153, 150);")
        self.profile_label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.profile_label.setObjectName("profile_label")
        self.exit_button = QtWidgets.QPushButton(Dialog)
        self.exit_button.setGeometry(QtCore.QRect(550, 70, 71, 31))
        self.exit_button.setStyleSheet("background-color: rgb(224, 27, 36);")
        self.exit_button.setObjectName("exit_button")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setGeometry(QtCore.QRect(130, 85, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.teacherlink_label = QtWidgets.QLabel(Dialog)
        self.teacherlink_label.setGeometry(QtCore.QRect(130, 112, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.teacherlink_label.setFont(font)
        self.teacherlink_label.setObjectName("teacherlink_label")
        self.userlink_label = QtWidgets.QLabel(Dialog)
        self.userlink_label.setGeometry(QtCore.QRect(130, 140, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userlink_label.setFont(font)
        self.userlink_label.setObjectName("userlink_label")
        self.userlink = QtWidgets.QLineEdit(Dialog)
        self.userlink.setGeometry(QtCore.QRect(300, 140, 151, 20))
        self.userlink.setObjectName("userlink")
        self.settings_button = QtWidgets.QPushButton(Dialog)
        self.settings_button.setGeometry(QtCore.QRect(440, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settings_button.setFont(font)
        self.settings_button.setStyleSheet(
            "background-color: rgb(53, 132, 228);")
        self.settings_button.setObjectName("settings_button")
        self.userlink_button = QtWidgets.QPushButton(Dialog)
        self.userlink_button.setGeometry(QtCore.QRect(460, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.userlink_button.setFont(font)
        self.userlink_button.setStyleSheet(
            "background-color: rgb(103, 226, 60);")
        self.userlink_button.setObjectName("userlink_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 80, 91, 91))
        self.label.setStyleSheet("border-radius:45px;\n"
                                 "background:rgb(255,255,255,0%);\n"
                                 "border: 2px solid black\n"
                                 "")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            "Z:/home/localhost/www/siteforman2020.loc/img/user/avatar.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.line.setText(_translate(
            "Dialog", "____________________________________________________________________________________________________"))
        self.models_button.setText(_translate("Dialog", "Моделі"))
        self.materials_button.setText(_translate("Dialog", "Матеріали"))
        self.profile_label.setText(_translate("Dialog", "  Профіль"))
        self.exit_button.setText(_translate("Dialog", "Вийти"))
        self.name_label.setText(_translate(
            "Dialog", "Прізвище Ім\'я по-Батькові"))
        self.teacherlink_label.setText(_translate(
            "Dialog", "Ваше посилання для приєднання: "))
        self.userlink_label.setText(_translate(
            "Dialog", "Уведіть посилання вчителя: "))
        self.settings_button.setText(_translate("Dialog", "Налаштування"))
        self.userlink_button.setText(_translate("Dialog", "Підтвердити"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
